### ISSUE TITLE
Notebook for Time Series Forecasting on a Public Dataset

### ISSUE THREAD

**Issue by suppathak** [redhat-et/customer-growth-model#3]
Creation of a notebook that demonstrates time series forecasting techniques using a publicly available dataset. This notebook aims to replicate our internal work while ensuring no confidential information is shared. The goal is to contribute to the open-source community and facilitate learning in time series forecasting.

**Comment by hemajv** [comment]
Notebooks added: https://github.com/redhat-et/customer-growth-model/tree/master/notebooks
